name: CI/CD with Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      # 4. Docker 로그인 (GitHub Secrets 사용)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t jinyeonseok/gear4camp:latest .

      # 6. Docker 이미지 푸시
      - name: Push Docker image
        run: docker push jinyeonseok/gear4camp:latest
