name: CI/CD with Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # gradle 빌드만(test는 진행 x)
      - name : gralde build with test
        run : ./gradlew clean build -x test

      # 4. Docker Compose 설치
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      # 5. Docker Compose로 모든 서비스 시작
      - name: Start services
        run: docker-compose -f docker-compose.test.yml up -d

      # 6. MySQL 컨테이너 준비 대기
      - name: Wait for MySQL to be ready
        run: sleep 20

      # 7. Gradle 테스트 수행 (테스트 전용)
      - name: Run tests inside Docker
        run: docker exec spring-app-test ./gradlew clean test

      # 8. Docker 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 9. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t jinyeonseok/gear4camp:latest .

      # 10. Docker 이미지 푸시
      - name: Push Docker image
        run: docker push jinyeonseok/gear4camp:latest